on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: cd socket/
      - run: npm install
      - run: node --version
      - run: pwd
      - run: node socket/index.js
      - run: node socket/express.js  